FROM node:18-alpine as builder
WORKDIR /app
COPY ./frontend .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
